#!/bin/sh

# Copyright 2025, UNSW
#
# SPDX-License-Identifier: BSD-2-Clause


# devmem 0x170000 b 0x00 && \
# sleep 2 && \
# devmem 0x170000 b 0x01 && \
# sleep 5 && \
# devmem 0x170000 b 0x02

devmem 0x170000 b 0x00 && \
ifconfig eth0 up && \
ifconfig && \
sleep 5 && \
udhcpc && \
(/root/echoit &) && \
export PYTHONPATH=$PTHONPATH:/ipbench/usr/lib/python3.12/site-packages/ && \
(/ipbench/usr/bin/ipbenchd -d -t &> output.txt &) && \
echo "Listening on the output.txt" && \
while true; do
    tail -f output.txt | while read -r line; do
        # echo $line
        if [[ "$line" == "\[run\] start" ]]; then
            # echo "[SCRIPT]: notify bench PD to start"
            devmem 0x170000 b 0x01
        fi
        if [[ "$line" == *"\[parse_common_opts\]: got line STOP"* ]]; then
            # echo "[SCRIPT]: notify bench PD to stop"
            devmem 0x170000 b 0x02
            cat /proc/interrupts
        fi
    done
done
