#!/bin/sh

# Copyright 2024, UNSW
#
# SPDX-License-Identifier: BSD-2-Clause

set -e

BLOCK_DEV=/dev/vda
MOUNT_POINT=/mnt

if ! ls "$BLOCK_DEV" >/dev/null;
then
    echo "ERROR: virtio block device does not exist!"
    exit 1
fi

if ! mount "$BLOCK_DEV" "$MOUNT_POINT";
then
    echo "WARNING: failed to mount block device, trying to create a FAT32 filesystem."
    if ! mkdosfs -F 32 -n "virtio_block_dev" "$BLOCK_DEV";
    then
        echo "ERROR: cannot create FAT32 filesystem on block device."
        exit 1
    fi
fi

echo "$BLOCK_DEV" successfully mounted at "$MOUNT_POINT"