# Copyright 2024, UNSW
#
# SPDX-License-Identifier: BSD-2-Clause

[package]
name = "vmm"
version = "0.1.0"
edition = "2021"
authors = ["Ivan Velickovic <i.velickovic@unsw.edu.au>"]
license = "BSD-2-Clause"

[[bin]]
name = "vmm"
path = "src/vmm.rs"

[dependencies]
sel4-microkit = { git = "https://github.com/seL4/rust-sel4", rev = "4edc3cdeada177b5d23e84ab06487cdd1fac0462" }
sel4-microkit-base = { git = "https://github.com/seL4/rust-sel4", rev = "4edc3cdeada177b5d23e84ab06487cdd1fac0462", features = ["extern-symbols"] }